### PR TITLE
Integrate Fia Colorado and Worldclim five minutes

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
We shall get the output as shown.
The program will take about 34 minutes to perform the join.

Screen Shot 2020-03-12 at 1 01 09 PM

**Comment by henrykironde** [comment]
**Steps.**

Use retriever to install the required datasets.

- `retriever install postgres worldclim-five`
- `retriever install postgres fia-colorado`

Integrate the data using pydataweaver

- `pydataweaver join postgres fia-colorado-plot-worldclim-five`

**Comment by henrykironde** [comment]
@ethanwhite this is ready.

**Comment by ethanwhite** [comment]
Works and looks great! Nice work @henrykironde!

**Pull request merged**
